version: '3'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./public:/srv/app/maptracker/public
      - ./src:/srv/app/maptracker/src
      - ./types:/srv/app/maptracker/types
      - ./babel.config.js:/srv/app/maptracker/babel.config.js
      - ./postcss.config.js:/srv/app/maptracker/postcss.config.js
      - ./tsconfig.json:/srv/app/maptracker/tsconfig.json
      - ./tslint.json:/srv/app/maptracker/tslint.json
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_URL=http://localhost:8080
      - VUE_APP_OAUTH_CLIENT_ID=EcaqpKbNOpK0Ho2MCSRQ6AdflHQOh7wQ
      - VUE_APP_OAUTH_CLIENT_DOMAIN=dev-puobt7a0.auth0.com
      - VUE_APP_OAUTH_AUDIENCE=http://localhost:3000/api/
      - VUE_APP_API_URL=http://localhost:8081
      - VUE_APP_PUSHBOTS_APP_ID=5d6e15e7b7941217b060aa53
      - VUE_APP_RECAPTCHA_SITE_KEY=6LdFh7cUAAAAAEtATezSvcm5abBNoJ2-2aFdpjAf

  nats:
    image: nats-streaming:0.11.2
    restart: on-failure
