version: '3'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./public:/srv/app/maptracker/public
      - ./src:/srv/app/maptracker/src
      - ./types:/srv/app/maptracker/types
      - ./babel.config.js:/srv/app/maptracker/babel.config.js
      - ./postcss.config.js:/srv/app/maptracker/postcss.config.js
      - ./tsconfig.json:/srv/app/maptracker/tsconfig.json
      - ./tslint.json:/srv/app/maptracker/tslint.json
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_URL=http://localhost:8080
      - VUE_APP_OAUTH_CLIENT_ID=
      - VUE_APP_OAUTH_CLIENT_DOMAIN=
      - VUE_APP_OAUTH_AUDIENCE=http://localhost:3000/api/
      - VUE_APP_API_URL=http://localhost:8081
      - VUE_APP_RECAPTCHA_SITE_KEY=
      - VUE_APP_STRIPE_PUBLISHABLE_KEY=
      - VUE_APP_STRIPE_PREMIUM_YEARLY_PLAN=
      - VUE_APP_ONESIGNAL_APP_ID=
      - VUE_APP_ENVIRONMENT=dev

  nats:
    image: nats-streaming:0.11.2
    restart: on-failure
