version: '3'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./public:/srv/app/maptracker/public
      - ./src:/srv/app/maptracker/src
      - ./.env.dev:/srv/app/maptracker/.env
      - ./babel.config.js:/srv/app/maptracker/babel.config.js
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true

  nats:
    image: nats-streaming:0.11.2
    restart: on-failure
